name: Build and Push Docker Image

on:
  push:
    branches:
      - main  # Trigger the action when changes are pushed to the `main` branch
  pull_request:
    branches:
      - main  # Trigger the action when a PR is made to the `main` branch

jobs:
  build:
    runs-on: ubuntu-latest  # Use the latest Ubuntu runner

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2  # Checkout the repository

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}  # Use GitHub Secrets for username
          password: ${{ secrets.DOCKER_TOKEN }}  # Use GitHub Secrets for password

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2  # Set up Docker Buildx for multi-platform builds

      - name: Cache Docker layers
        uses: actions/cache@v4
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.run_number  }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Build Docker image
        run: |
          docker build -t dipakyadav/azure-blob-explorer:${{ github.run_number }} .
        
      - name: Push Docker image
        run: |
          docker push dipakyadav/azure-blob-explorer:${{ github.run_number }}
